###########################
### 1. General settings ###
###########################


work_directory: "/Users/aishkrishnamohan/FRETNet-Designer/Test/"  # The directory containing the data and structures of interest. Outputs of this code will be saved in subfolders.
output_directory: "/Users/aishkrishnamohan/FRETNet-Designer/Test/outputs/" # Subfolder to save output files in. Will be created if it doesn't exist
input_directory: "/Users/aishkrishnamohan/FRETNet-Designer/Test/inputs/" # name of a subfolder from a previous run from which things like AVs can be reloaded rather than re-calculated
dependancy_directory: "/Users/aishkrishnamohan/FRETNet-Designer/Script_Dependancies" # Directory containing the Python implementation of DCA and other custom functions
input_structures:     # Input structure files, must be list of strings which are names of files along with their paths
  - "/Users/aishkrishnamohan/FRETNet-Designer/Test/RBP_closed_fromSBM+DCA.pdb"
  - "/Users/aishkrishnamohan/FRETNet-Designer/Test/RBP_open_fromSBM+DCA.pdb"
  - "/Users/aishkrishnamohan/FRETNet-Designer/Test/RBP_Twisted_allatom.pdb"
fretraj_fix_our_side: true   # Switch for whether we want to use logic which fixes the fretraj serial bug on our side or not. Previously we would hand-modify their package for a new install.
Randomization Seed: 10

###########################
### 1.1 Figure settings ###
###########################


figure_parameters:
  legend.fontsize: "xx-large"
  figure.figsize: [10, 10]
  axes.labelsize: "xx-large"
  axes.titlesize: "xx-large"
  xtick.labelsize: "xx-large"
  ytick.labelsize: "xx-large"
  lines.linewidth: 1
  font.family: "Arial"
  ps.fonttype: 42
  pdf.fonttype: 42

#series of settings for whether or not to do a step, or whether to load a previous run or re-perform the action of a module\
#these accept "False" (F), "True" (T), and "Load" (L) for ignoring, performing, or loading a previous run, respectively
#Some parameters accept "Specify" (S), an option like load, but it lets you point to a specific folder/set of files/file to load that was pre-generated, rather than using 
#all outputs from the folder specified in "input"

do_make_MSA: true
do_DCA: true
do_conservation_score: true
Do_AV: true


##########################################
### 2. Domain and Residue Restrictions ###
##########################################


define_domains: true  # defines domains between which sites should be tested. This prevents sites from within the same domains 
                      # being tested against one another. this essentially is a time saver, as sites within separate domains 
                      # which are mutually re-orienting are likely to provide higher contrast than sites within a single domain
domain_bounds:        # domain bounds accepts a list of lists containing the domain names, start residue, and end residue (in terms 
                      # of the input file indexing). 
                      # ['Dom3', 235, 271]] #takes name of domain plus the residue limits in terms of indices loaded by mdtraj
  - ['Dom1', 1, 103]
  - ['Dom2', 104, 271]   
exclude_residues: false       # exluded residues allows particular residues to be excluded. This will remove the residue from any relevant lists if present,
                              # but will not perturb the domain definitions,
                              # ranges of residues can be specified to be excluded as a list of [start, stop] inclusive. these will be popped out and 
                              # generate individual entries into the exclusion list, so this is only for convenience. These are ignorby some analyses, 
                              # and those analyses will be performed across the whole sequence. excluded really just marks these sitesed "bad" as if 
                              # some parameter eliminated them, such as low SASA.
                              # domain bounds really works at the pair level.
excluded_residues:          # in this example, first two entries are redundant with domain bounds, 3rd eliminates a site in domain 2. Currently must feed this a list (even if empty)
  - 61
  - 151
  - [152, 155]
  - 246

############################  
### 3. MSA file settings ###
############################
generate_MSA: true   # Whether to generate an MSA during run-time or the user will provide a pre-generated MSA file. 
                     # Must ensure correct formating for DCA. Too many MSA formats to account for all of them. 
                     # Sequences should be padded to align exactly along the input structure sequence using '-' placeholder character.
                     # Each sequence should appear on a single line, with lines separated by >header lines.

pregenerated_MSA_file: "/Users/aishkrishnamohan/FRETNet-Designer/Test/inputs/OutMSA_filtered30.msa"   #location of pregenerated MSA file if generate_MSA == False


###################################################
### 3.1 settings for MSA generation at run-time ###
###################################################

input_seed: "Input_Structure_FASTA.fasta"  # location of input seed sequence file
max_align_gaps: "30"  # max number allowed gaps in sequences to allow for in filtering
outputHMM: 'OutHMM.hmm'  # ouput HMM file to generate.
database_path: '/Users/aishkrishnamohan/Pfam-A.fasta.gz'  # database location
outputMSA_filename: 'OutMSA.msa'  # creates full sequence file with this name as well as filtered with this name +'_filtered<gapnumber>'
hmmer_bin: '/Users/aishkrishnamohan/hmmer/src/'  # location of hmmer bin for accessing hmmer CLI tools
easel_miniapps: '/Users/aishkrishnamohan/hmmer/easel/miniapps/'  # location of easel miniapps for access to easel CLI tools
filter_pfam_path: '/Users/aishkrishnamohan/FRETNet-Designer/filter_pfam_args.py'  # filter pfam script path

#######################
### 4. DCA settings ###
#######################

pregenerated_DCA: True  # whether DCA was pre-run. if true, need to specify a DCA output file
pregenerated_DCA_file: "/Users/aishkrishnamohan/FRETNet-Designer/Test/outputs/outDCA.dat"
DCA_output: "/Users/aishkrishnamohan/FRETNet-Designer/Test/outputs/outDCA.dat"


###############################
### 5. SASA and AV Settings ###
###############################

contact_cutoff: 0.5  # nm. cutoff to convert residue to "bad" residue based on inter-residue contacts.
SASA_cutoff: 0.2  # nm^2 cutoff below which the low SASA of the residue disqualifies it from labeling
contact_cutoff_mode: average  # average or individual. Decides whether to check against the average contact or all individually
SASA_cutoff_mode: average  # as above for contacts

generate_dye_parameters_file: True  # True/Load/Specify (need dye parameters for AV sims)
specified_dye_parameters_file: null

Save_AVs_pkl: True  # Only used if Do_AV=True, saves AVs into a directory as appropriate for reloading
Save_AVs_xyz: True  # only used if Do_AV=True, saves AV xyz files for visualization
AV_label_atom: CA  # must be an atom all residues have. can add exceptions later
Considered_Atoms: Local_Labeled_Only  # which atoms to account for in AV simulations.
Residues_Range_to_Ignore: 1

basic_dye_parameters:
  Position:
    Al488C5:
      linker_length: 20.5
      linker_width: 2.5
      dye_radius1: 5.0
      dye_radius2: 4.5
      dye_radius3: 1.5
    Al647C2:
      linker_length: 21.0
      linker_width: 2.5
      dye_radius1: 7.15
      dye_radius2: 4.5
      dye_radius3: 1.5
  Distance:
    Al488C5-Al647C2:
      R0: 52.0
      n_dist: 10000

N_AV_points_mode: all  # all, average, or none
N_AV_points_threshold: 200
